# Numpy

In [4]:
import numpy as np

## Basic

### Array Slicing

In [8]:
# 1-D Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[1:5:2])
print(arr[::2]) # Every other element (third value is step size)

[2 3 4 5]
[2 4]
[1 3 5 7]


In [14]:
# 2-D Slicing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4]) # First row, then slicing
print(arr[0:2, 2]) # Both rows, then access second element in both
print(arr[0:5, 2]) # Note how if we specify more rows than exists it doesn't complain
print(arr[0:2, 1:4])

# Summary: The format to access is array[rows, columns], rows and columns can take scalar values (access specific row/column) and also slices.

[7 8 9]
[3 8]
[3 8]
[[2 3 4]
 [7 8 9]]


### Data Types
Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [23]:
# Check data type of array
arr = np.array([1, 2, 3, 4])
print(arr.dtype) 
print("////////////////////")
# Create array of predefined data type. 
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)
arr = np.array([1, 2, 3, 4], dtype='i4') # For i, u, f, S and U we can define size as well. In this case 4 bytes integer.
print(arr)
print(arr.dtype)
print("////////////////////")
# Casting types
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

int64
////////////////////
[b'1' b'2' b'3' b'4']
|S1
[1 2 3 4]
int32
////////////////////
[1 2 3]
int32


### Array Copy and View
Copy is a new array, and the view is just a view of the original array:
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [72]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()

# Every NumPy array has the attribute base that returns None if the array owns the data.
print(arr.base) # Returns None
print(x.base) # Returns None
print(y.base) # Returns original data

None
None
[1 2 3 4 5]


### Shape
The shape of an array is the number of elements in each dimension.

In [38]:
# 1D
arr = np.array([1, 2, 3, 4])
print(arr)
print('Shape of array :', arr.shape)
print("/////////////")
# 2D
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print('Shape of array :', arr.shape)
print("/////////////")
# 3D
arr = np.array([[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]])
print(arr)
print('Shape of array :', arr.shape)
print("/////////////")
# 4D
arr = np.array([[[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]], [[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]])
print(arr)
print('Shape of array :', arr.shape)
print("/////////////")
# 5D
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('Shape of array :', arr.shape)

[1 2 3 4]
Shape of array : (4,)
/////////////
[[1 2 3 4]
 [5 6 7 8]]
Shape of array : (2, 4)
/////////////
[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]

 [[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
Shape of array : (2, 3, 4)
/////////////
[[[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]


 [[[1 2 3 4]
   [1 2 3 4]
   [1 2 3 4]]]]
Shape of array : (2, 1, 3, 4)
/////////////
[[[[[1 2 3 4]]]]]
Shape of array : (1, 1, 1, 1, 4)


### Reshaping
By reshaping we can add or remove dimensions or change number of elements in each dimension.
**Can We Reshape Into any Shape?** Yes, as long as the elements required for reshaping are equal in both shapes.

**Note:** There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.

In [47]:
# Reshape From 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Current Shape: ", arr.shape)
newarr = arr.reshape(4, 3) # 4x3=12
print("New Shape: ", newarr.shape)
print(newarr)
print("//////////////////")
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Current Shape: ", arr.shape)
newarr = arr.reshape(4, 1, 3)  # 4x1x3=12
print("New Shape: ", newarr.shape)
print(newarr)
print("//////////////////") 
# IMPORTANT: Reshaping returns a view!
print(newarr.base)
print("//////////////////") 
# Unknown dimension. You do not have to specify an exact number for one of the dimensions in the reshape method. 
# Pass -1 as the value, and NumPy will calculate this number for you.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)
print("//////////////////") 
# Flattening array
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

Current Shape:  (12,)
New Shape:  (4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
//////////////////
Current Shape:  (12,)
New Shape:  (4, 1, 3)
[[[ 1  2  3]]

 [[ 4  5  6]]

 [[ 7  8  9]]

 [[10 11 12]]]
//////////////////
[ 1  2  3  4  5  6  7  8  9 10 11 12]
//////////////////
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
//////////////////
[1 2 3 4 5 6]



### NumPy Array Iterating
Instead of using for loops to iterate through each dimension one by one, we can use nditer(). Its a helping function that can be used from very basic to very advanced iterations. 

In [52]:
# 3D Array
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr): # Note how no nested loops are necessary
  print(x)
print("///////////////")
# Casting datatypes while looping. We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements 
# while iterating.NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other 
# space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

print("///////////////")
# Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
///////////////
np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
///////////////
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


### NumPy Joining Array
In NumPy we join arrays by axes. We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [62]:
# Join two arrays along
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
print("////////////////")
# Join two arrays along axis 1 (rows)
arr1 = np.array([[1, 2], [3, 4]])  # 1, 2 | 5, 6 -> 1 2 5 6
arr2 = np.array([[5, 6], [7, 8]])  # 3, 4 | 7, 8 -> 3 4 7 8
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)
print("////////////////")
# Join using stack function. Stacking is same as concatenation, the only difference is that stacking is done along a new axis. We can concatenate 
# two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)
print("////////////////")
# NumPy provides a helper function: hstack() to stack along rows.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)
print("////////////////")
# NumPy provides a helper function: vstack()  to stack along columns.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)
print("////////////////")
# NumPy provides a helper function: dstack() to stack along height, which is the same as depth.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)


[1 2 3 4 5 6]
////////////////
[[1 2 5 6]
 [3 4 7 8]]
////////////////
[[1 4]
 [2 5]
 [3 6]]
////////////////
[1 2 3 4 5 6]
////////////////
[[1 2 3]
 [4 5 6]]
////////////////
[[[1 4]
  [2 5]
  [3 6]]]


### NumPy Splitting Array
Splitting is reverse operation of Joining. We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

**Note:** We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

**Note:** The return value of the array_split() method is an array containing each of the split as an array.

In [85]:
# Split array 1D
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)
print("////////////////")
# Split array 2D
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)
# Uneven split
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)
print("////////////////")
# Oversplit
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 10)
print(newarr)
print("////////////////")
# In addition, you can specify which axis you want to do the split around.
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])
newarr = np.array_split(arr, 3, axis=1)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
////////////////
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]
////////////////
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]
////////////////
[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [87]:
# An alternate solution is using hsplit() opposite of hstack(). Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit()
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


### NumPy Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

In [93]:
# Search array
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4) # Returns indexes of matches
print(x)
print("////////////////")
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)
print("////////////////")
# There is a method called searchsorted() which performs a
# binary search in the array, and returns the index where the specified 
# value would be inserted to maintain the search order. 
# It is assumed to be used on sorted arrays.
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7) # The number 7 should be inserted on index 1 to remain the sort order. It returns the first index where the number 7 is no longer larger than the next value.
print(x)
print("////////////////")
# Search from right side
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right') # Find the indexes where the value 7 should be inserted, starting from the right
print(x)
print("////////////////")
# Search for multiple values
arr = np.array([1, 3, 5, 7])
x = np.searchsorted(arr, [2, 4, 6])
print(x)

(array([3, 5, 6]),)
////////////////
(array([1, 3, 5, 7]),)
////////////////
1
////////////////
2
////////////////
[1 2 3]


### NumPy Sorting Arrays
The NumPy ndarray object has a function called sort(), that will sort a specified array.

**Note:** This method returns a copy of the array, leaving the original array unchanged.

In [98]:
# Sort Array 1D 
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))
print("////////////////")
# Sort Array 2D 
arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))
print("////////////////")

[0 1 2 3]
////////////////
[[2 3 4]
 [0 1 5]]
////////////////


### NumPy Filter Array
Getting some elements out of an existing array and creating a new array out of them is called filtering. In NumPy, you filter an array using a boolean index list (similar to pandas).

In [102]:
# Boolean indexing example
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)
print("////////////////")
# The common use is to create a filter array based on conditions.
arr = np.array([41, 42, 43, 44])
filter_arr = []
for element in arr:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)
print("////////////////")
# Or using a more concise form
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[41 43]
////////////////
[False, False, True, True]
[43 44]
////////////////
[False False  True  True]
[43 44]


## Random